### ISSUE TITLE
2 Questions: Why is ISOCountry.numeric not marked unique? Why arent't you using on of the unique fields as pk?

### ISSUE THREAD

**Issue by tback** [ocwebteam/django-diplomat#1]
Hi,

as I said it in the title - I've got two questions for you:
1. Why is ISOCountry.numeric not marked unique?
2. Why aren't you using one of the unique fields as pk for either ISOCountry or ISOLanguage?

Thanks a lot,

tback

**Comment by cilcoberlin** [comment]
Thanks for the questions.

ISOCountry.numeric isn't unique because of a bug in pycountry where Singapore and Sint Maarten are both assigned the numeric value of 702.  If it weren't for that, it would be unique.

As for using one of the unique fields as a PK, I can't provide any definitive reason, but I was probably influenced by paranoia that pycountry would change or have a bug that might make an assumption of uniqueness prove to be incorrect, a general preference for surrogate keys, and not having seen many Django apps that use something other than the AutoField as a primary key.
